version: '3.8'
services:
    web:
        container_name: ysepz_web_container
        build:
          context: ""
          dockerfile: Dockerfile.web.dev
        #image: "ghcr.io/davecoulter/yse_pz:latest"
        image: "ghcr.io/frbs/ffff_pz:latest"
        #image: "local/ffff_pz_web:dev"
        platform: linux/amd64
        volumes:
            - ${VOL}:/app
            #- ${PATH_FILES}:/PATH_FILES
            # X tinkering
            #- ./entrypoints:/app/Entrypoints
        links:
            - yse_db
        #command: bash ./Entrypoints/docker-compose-up-entrypoint.sh
        command: python3 manage.py runserver 0.0.0.0:8000
        ports:
        - "8000:8000"
        environment:
          CONDA_DEFAULT_ENV: base
          _: /opt/conda/bin/python
          CONDA_EXE: /opt/conda/bin/conda
          SHLVL: 1
          CONDA_PYTHON_EXE: /opt/conda/bin/python
          CONDA_SHLVL: 1
          CONDA_PROMPT_MODIFIER: (base)
          PROJ_LIB: /opt/conda/share/proj
          CONDA_PREFIX: /opt/conda
          DB_CONFIG: /opt/project/db_configuration
        env_file:
          - ".env"
        depends_on:
          yse_db:
            condition: service_healthy
    yse_db:
      container_name: ysepz_db_container
      image: "mysql:8.0.25"
      platform: linux/amd64
      command: mysqld --default-authentication-plugin=mysql_native_password
      ports:
        - "${LOCAL_DB_PORT}:3306"
      volumes:
        - ${VOL_DB}:/var/lib/mysql
        - ./db_init/db_configuration:/etc/mysql/conf.d
        - ./db_init/init.sql:/docker-entrypoint-initdb.d/1.sql
        - ./db_init/YSE_Initial_Schema.sql:/docker-entrypoint-initdb.d/2.sql
        - ./db_init/YSE_followupstatus_insert.sql:/docker-entrypoint-initdb.d/3.sql
        - ./db_init/YSE_rest_of_tables_insert.sql:/docker-entrypoint-initdb.d/4.sql
        - ./db_init/YSE_django_migrations_insert.sql:/docker-entrypoint-initdb.d/5.sql
        - ./db_init/YSE_create_users.sql:/docker-entrypoint-initdb.d/6.sql
        - ${VOL_DB_LOG}:/var/log/mysql
        - ${VOL_GHOST}:/app/ghost_logs
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PWD}
      healthcheck:
        test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
        timeout: 20s
        retries: 10
# X tinkering
#    yse_nginx:
#      container_name: ysepz_web_nginx_container
#      image: "nginx:1.21-alpine"
#      ports:
#        - "${LOCAL_HTTP_PORT}:80"
#      volumes:
#        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#        - ${STATIC_VOL}:/static
#      depends_on:
#        - web

